#manejamos todas las maquinas virtuales, configuracion del entorno
version: '3.9'
services:
  db:
    image: mysql:latest
    container_name: base_datos
    environment:
      - MYSQL_DATABASE=taller
      - MYSQL_ROOT_PASSWORD=db_password
    ports: 
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-dump:/docker-entrypoint-initdb.d
    #networks:
     # dto-red:
      #  ip4_address: 192.168.10.10/24
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    #networks:
     # dto-red:
      #  ip4_address: 192.168.10.11/24
  web-datos:
    container_name: servidor-web
    build:
      context: .
      dockerfile: ./datos/Dockerfile
    volumes:
      - ./datos/src:/var/www/html/src
      - ./datos/public:/var/www/html/public
      #- ./www:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    #networks:
     # dto-red:
      #  ip4_address: 192.168.10.12/24
  web-negocio:
    container_name: servidor-negocio
    build:
      context: .
      dockerfile: ./negocio/Dockerfile
    volumes:
      - ./negocio/src:/var/www/html/src
      - ./negocio/public:/var/www/html/public
      #- ./www:/var/www/html
    ports:
      - 9000:80
    depends_on:
      - web-datos
    #networks:
     # dto-red:
      #  ip4_address: 192.168.10.13/24
secrets:
  db_password:
    file: db_password.txt
volumes:
  db-dump:
  mysql:
  www:
  negocio: